### ISSUE TITLE
Unable to build with mingw

### ISSUE THREAD

**Issue by naoto-aoki-fy** [jhpc-quantum/RIKEN-braket#154]
## Issue description

Unable to build `bra` with mingw on msys2.
The error log: [make_log.txt](https://github.com/user-attachments/files/17272570/make_log.txt)

## Steps to reproduce

commit id: 91c2a92e272f8c4b01a9e2013902110b27b96db2

- install `msys2`
- launch mingw64 terminal
- install packages: `pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-msmpi mingw-w64-x86_64-make mingw-w64-x86_64-boost`
- `script -f -c "mingw32-make.exe -k" make_log.txt`

**Comment by naoki-yoshioka** [comment]
I have pushed a branch [bugfix](https://github.com/jhpc-quantum/RIKEN-braket/tree/bugfix) to fix this problem.
Could you git-pull it and check if it becomes to be able to build?

**Comment by naoki-yoshioka** [comment]
The errors about wrong concatenation of "MPI::" and "datatype" are solved by the bugfix commit.
However, the other errors are something like there are no MPI namespace in the environment.
It is difficult to solve this problem, therefore I will close this issue.

Probably I will change the requirement of the environment of braket about MPI near future.
